// <auto-generated />
using System;
using AiCostMonitor.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AiCostMonitor.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AiCostMonitor.Core.Entities.UsageRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("CacheCreationTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("cache_creation_tokens");

                    b.Property<long>("CacheReadTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("cache_read_tokens");

                    b.Property<decimal>("CostUsd")
                        .HasColumnType("numeric(18, 8)")
                        .HasColumnName("cost_usd");

                    b.Property<long>("InputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("input_tokens");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<long>("OutputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("output_tokens");

                    b.Property<DateTimeOffset>("PeriodEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_end");

                    b.Property<DateTimeOffset>("PeriodStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_start");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<Guid>("ProviderKeyId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_key_id");

                    b.Property<string>("RawJson")
                        .HasColumnType("text")
                        .HasColumnName("raw_json");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_usage_records");

                    b.HasIndex("Provider", "Model")
                        .HasDatabaseName("ix_usage_records_provider_model");

                    b.HasIndex("UserId", "PeriodStart")
                        .HasDatabaseName("ix_usage_records_user_id_period_start");

                    b.HasIndex("ProviderKeyId", "Model", "PeriodStart")
                        .IsUnique()
                        .HasDatabaseName("ix_usage_records_provider_key_id_model_period_start");

                    b.ToTable("usage_records", (string)null);
                });

            modelBuilder.Entity("AiCostMonitor.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("AiCostMonitor.Core.Entities.UserProviderKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EncryptedApiKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("encrypted_api_key");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("KeySuffix")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key_suffix");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_provider_keys");

                    b.HasIndex("UserId", "Provider", "Label")
                        .HasDatabaseName("ix_provider_keys_user_id_provider_label");

                    b.ToTable("provider_keys", (string)null);
                });

            modelBuilder.Entity("AiCostMonitor.Core.Entities.UsageRecord", b =>
                {
                    b.HasOne("AiCostMonitor.Core.Entities.UserProviderKey", "ProviderKey")
                        .WithMany("UsageRecords")
                        .HasForeignKey("ProviderKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usage_records_provider_keys_provider_key_id");

                    b.HasOne("AiCostMonitor.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usage_records_users_user_id");

                    b.Navigation("ProviderKey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AiCostMonitor.Core.Entities.UserProviderKey", b =>
                {
                    b.HasOne("AiCostMonitor.Core.Entities.User", "User")
                        .WithMany("ProviderKeys")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_provider_keys_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AiCostMonitor.Core.Entities.User", b =>
                {
                    b.Navigation("ProviderKeys");
                });

            modelBuilder.Entity("AiCostMonitor.Core.Entities.UserProviderKey", b =>
                {
                    b.Navigation("UsageRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
